<!-- Usersnap feedback -->
<script type="text/javascript">
   var _usersnapconfig = {
       apiKey: 'efc0c5d1-c4c5-4260-8cea-b16a2406faef',
       valign: 'bottom',
       halign: 'right',
       tools: ["pen", "highlight", "blackout"],
       lang: 'en',
       commentBox: true,
       emailBox: true,
       emailBoxValue: document.sessionState.userid
   };
   (function() {
       var s = document.createElement('script');
       s.type = 'text/javascript';
       s.async = true;
       s.src = '//api.usersnap.com/usersnap.js';
       var x = document.getElementsByTagName('head')[0];
       x.appendChild(s);
   })();
</script>

<!-- Intercom -->
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://static.intercomcdn.com/intercom.v1.js';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}};})()</script>
<!-- Intercom -->