<div class="footerBar">
  <div class="container"> 
  	<footer> 
     	 <div class="row-fluid">
          <div class="span12 footerLinks" >
              <ul>
                <li><a href="/team">Team</a></li>|
                <li><a href="/careers">Careers</a></li>|
                <li><a href="/press">Press</a></li>|
                <li><a href="http://blog.sharewave.com">Blog</a></li>
              </ul>             
          </div>
     	 </div>
       <div class="row-fluid" id="copyrightBar">
        <a href="/privacy"><span class="copyright pull-left">LEGAL INFORMATION</span></a>
       	<span class="copyright pull-right">COPYRIGHT 2013 SHAREWAVE LLC, ALL RIGHTS RESERVED</span>
       </div>
    </footer>
  </div>
</div>

