<!-- Usersnap feedback -->
<script type="text/javascript">
   var _usersnapconfig = {
       apiKey: 'efc0c5d1-c4c5-4260-8cea-b16a2406faef',
       valign: 'bottom',
       halign: 'right',
       tools: ["pen", "highlight", "note"],
       lang: 'en',
       commentBox: true,
       emailBox: true,
       emailBoxValue: document.sessionState.userid
   };
   (function() {
       var s = document.createElement('script');
       s.type = 'text/javascript';
       s.async = true;
       s.src = '//api.usersnap.com/usersnap.js';
       var x = document.getElementsByTagName('head')[0];
       x.appendChild(s);
   })();
</script>