<div class="footerBar">
    <div class="container scaling">
        <footer>
            <div class="row-fluid">
                <div class="span12 footerLinks" >
                    <ul>
                        <li><a href="/team">Team</a></li>|
                        <li><a href="/careers">Careers</a></li>|
                        <li><a href="/press">Press</a></li>|
                        <li><a href="http://blog.sharewave.com">Blog</a></li>
                    </ul>
                </div>
            </div>
            <div class="row-fluid" id="copyrightBar">
                <div class="copyrightLinks">
                    <ul>
                        <li><a href="/privacy">PRIVACY POLICY</span></a></li>|
                        <li><a href="/terms">TERMS OF USE</span></a></li>
                    </ul>
                </div>
                <span class="copyright pull-right hidden-phone">COPYRIGHT 2013 SHAREWAVE LLC, ALL RIGHTS RESERVED</span>
                <br class="visible-phone">
                <span class="copyright pull-left visible-phone">COPYRIGHT 2013 SHAREWAVE LLC, ALL RIGHTS RESERVED</span>
            </div>
        </footer>
    </div>
</div>

