<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link type="text/css" rel="stylesheet" href="css/bootstrap.css">
<link type="text/css" rel="stylesheet" href="css/bootstrap-responsive.css">
<link type="text/css" rel="stylesheet" href="css/MVP.css">
<link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800">

 <script src="brijj/brijj.js"></script>
 <script src="js/jquery-1.8.3.js"></script>
 <script src="script/bootstrap.js"></script>
 <script src="js/angular.js"></script>
 <script src="js/angular-ui.js"></script>
 <script src="js/angular-resource.js"></script>
 <script src="js/ui-bootstrap-tpls-0.2.0.js"></script>

<link type="text/css" rel="stylesheet" href="css/introjs.css">
<script src="js/intro.js"></script>

<!-- <script src="js/common.js"></script> -->