<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link type="text/css" rel="stylesheet" href="/lib/bootstrap/bootstrap.css">
<link type="text/css" rel="stylesheet" href="/lib/bootstrap/bootstrap-responsive.css">
<link type="text/css" rel="stylesheet" href="/cmn/MVP.css">

<link type="text/css" rel="stylesheet" href="/cmn/fonts/logo/style.css">
<link type="text/css" rel="stylesheet" href="/cmn/fonts/icons/style.css">
