
<!-- Fonts -->
<script type="text/javascript">
WebFontConfig = { fontdeck: { id: '35219' } };

(function() {
  var wf = document.createElement('script');
  wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
  '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
  wf.type = 'text/javascript';
  wf.async = 'true';
  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(wf, s);
})();
</script>
<!-- logo font -->

<script src="/lib/jquery/jquery-1.8.3.js"></script>
<script src="/lib/bootstrap/bootstrap.js"></script>
<script src="/lib/angular/angular.js"></script>
<script src="/lib/angular/angular-ui.js"></script>
<script src="/lib/angular/ui-utils.js"></script>
<script src="/lib/angular/angular-resource.js"></script>
<script src="/lib/angular/ui-bootstrap-tpls-0.4.0.js"></script>
<script src="/lib/angular/ui-utils/event.js"></script>
<script src="/brijj/aBrijj.js"></script>
<script src="/lib/moment.min.js"></script>

