<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link type="text/css" rel="stylesheet" href="/lib/bootstrap/bootstrap.css">
<link type="text/css" rel="stylesheet" href="/lib/bootstrap/bootstrap-responsive.css">
<link type="text/css" rel="stylesheet" href="/lib/fontawesome/css/font-awesome.css">
<link type="text/css" rel="stylesheet" href="/cmn/MVP.css">
<link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800|Arvo|Dosis:700">
 <script src="/brijj/brijj.js"></script>
 <script src="/lib/jquery/jquery-1.8.3.js"></script>
 <script src="/lib/bootstrap/bootstrap.js"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.1.5/angular.min.js"></script>
 <script src="/lib/angular/angular-ui.js"></script>
 <script src="/lib/angular/angular-resource.js"></script>
 <script src="/lib/angular/ui-bootstrap-tpls-0.2.0.js"></script>
 <script src="/lib/angular/ui-utils/event.js"></script>

<link type="text/css" rel="stylesheet" href="/lib/introjs.css">
<script src="/lib/intro.js"></script>

<!-- <script src="js/common.js"></script> -->
