<!--[if lt IE 9]>
    <script type="text/javascript">
        document.location.href = '/err/browser.html';
    </script>
<![endif]-->

<script src="/lib/jquery/jquery-1.8.3.js"></script>
<script src="/lib/bootstrap/bootstrap.js"></script>
<script src="/lib/angular/angular.js"></script>
<script src="/lib/angular/angular-ui.js"></script>
<script src="/lib/angular/ui-utils.js"></script>
<script src="/lib/angular/angular-resource.js"></script>
<script src="/lib/angular/ui-bootstrap-tpls-0.4.0.js"></script>
<script src="/lib/angular/ui-utils/event.js"></script>
<script src="/brijj/aBrijj.js"></script>
<script src="/lib/moment.min.js"></script>
<script src="/cmn/nav.js"></script>

<script>
        window.console = window.console || {};
        window.console.log = window.console.log || function() {};
</script>

<meta property="og:image" content="/img/ike-social.png" />
<meta property="og:image" content="https://s3.amazonaws.com/sharewave/www/images/ike-social.png" />
<meta property="og:title" content="Sharewave" />
<meta property="og:description" content="The best way to manage your shareholders" />
<meta property="og:url" content="https://sharewave.com" />