<script type="text/javascript">
var _kmq = _kmq || [];
if ((window.location.hostname == "www.sharewave.com" || window.location.hostname == "sharewave.com") && document.location.pathname.indexOf("timeout") == -1) {
    var _kmk = _kmk || '6fca73192583d11a98c3793b72f5975712a17c5c';
    function _kms(u){
      setTimeout(function(){
        var d = document, f = d.getElementsByTagName('script')[0],
        s = d.createElement('script');
        s.type = 'text/javascript'; s.async = true; s.src = u;
        f.parentNode.insertBefore(s, f);
      }, 1);
    }
    _kms('//i.kissmetrics.com/i.js');
    _kms('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');
}
</script>

<!--[if lt IE 9]>
    <script type="text/javascript">
        document.location.href = '/err/browser.html';
    </script>
<![endif]-->

<script src="/lib/jquery/jquery-1.8.3.js"></script>
<script src="/lib/bootstrap/bootstrap.js"></script>
<script src="/lib/angular/angular.js"></script>
<script src="/lib/angular/angular-route.js"></script>
<script src="/lib/angular/angular-sanitize.js"></script>
<script src="/lib/angular/angular-ui.js"></script>
<script src="/lib/angular/ui-utils.js"></script>
<script src="/lib/angular/angular-resource.js"></script>
<script src="/lib/angular/ui-bootstrap-tpls-0.4.0.js"></script>
<script src="/lib/angular/ui-utils/event.js"></script>
<script src="/lib/modernizr/modernizr.js"></script>
<script src="/lib/placeholders.min.js"></script>
<script src="/brijj/aBrijj.js"></script>
<script src="/lib/moment.min.js"></script>
<script src="/cmn/nav.js"></script>
<script src="/lib/usersnap/jquery.usersnap-0.1.0.js"></script>

<script>
        window.console = window.console || {};
        window.console.log = window.console.log || function() {};
</script>

<meta property="og:image" content="/img/ike-social.png" />
<meta property="og:image" content="https://s3.amazonaws.com/sharewave/www/images/ike-social.png" />
<meta property="og:title" content="Sharewave" />
<meta property="og:description" content="The best way to manage shareholders" />
<meta property="og:url" content="https://sharewave.com" />