<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link type="text/css" rel="stylesheet" href="/lib/bootstrap/bootstrap.css">
<link type="text/css" rel="stylesheet" href="/lib/bootstrap/bootstrap-responsive.css">
<link type="text/css" rel="stylesheet" href="/lib/bootstrap/bootstrap-tagsinput.css">
<link type="text/css" rel="stylesheet" href="/lib/datepicker/bootstrap-datepicker.css">
<link type="text/css" rel="stylesheet" href="/lib/select2/select2.css">
<link type="text/css" rel="stylesheet" href="/cmn/MVP.css">
<link type="text/css" rel="stylesheet" href="/home/home.css">

<link type="text/css" rel="stylesheet" href="/cmn/fonts/logo/style.css">
<link type="text/css" rel="stylesheet" href="/cmn/fonts/icons/style.css">
<link type="text/css" rel="stylesheet" href="/cmn/fonts/fselliot/elliot.css">
<link type="text/css" rel="stylesheet" href="/cmn/newnav.css">
<link type="text/css" rel="stylesheet" href="/cmn/internal-rail/right-rail.css">

<link href='https://fonts.googleapis.com/css?family=Arizonia' rel='stylesheet' type='text/css'>
