<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link type="text/css" rel="stylesheet" href="/lib/bootstrap/bootstrap.min.css">
<link type="text/css" rel="stylesheet" href="/lib/bootstrap/bootstrap-responsive.css">
<link type="text/css" rel="stylesheet" href="/cmn/MVP.css">
<!-- Fonts -->
<link type="text/css" rel="stylesheet" href="/lib/fontawesome/css/font-awesome.css">
<script type="text/javascript">
WebFontConfig = { fontdeck: { id: '35219' } };

(function() {
  var wf = document.createElement('script');
  wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
  '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
  wf.type = 'text/javascript';
  wf.async = 'true';
  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(wf, s);
})();
</script>
<!-- logo font -->
<link type="text/css" rel="stylesheet" href="/cmn/fonts/logo/style.css">
<link type="text/css" rel="stylesheet" href="/cmn/fonts/icons/style.css">

<script src="/lib/jquery/jquery-1.8.3.min.js"></script>
<script src="/lib/bootstrap/bootstrap.min.js"></script>
<script src="/lib/angular/angular.min.js"></script>
<script src="/lib/angular/angular-ui.js"></script>
<script src="/lib/angular/ui-utils.js"></script>
<script src="/lib/angular/angular-resource.js"></script>
<script src="/lib/angular/ui-bootstrap-tpls-0.4.0.js"></script>
<script src="/lib/angular/ui-utils/event.js"></script>
<script src="/brijj/aBrijj.js"></script>
<script src="/lib/moment.min.js"></script>

